
language: objective-c
osx_image: xcode8.2

env:
  global:
    - LC_CTYPE=en_US.UTF-8
    - LANG=en_US.UTF-8
    - WORKSPACE=PopcornTime.xcworkspace
    - IOS_SDK=iphonesimulator10.2
    - TVOS_SDK=appletvsimulator10.2
script:
  - set -o pipefail
  - xcodebuild -version
  - xcodebuild -showsdks
  - xcodebuild -workspace "$WORKSPACE" -scheme "PopcornTime tvOS" -sdk "$TVOS_SDK" -configuration Release | xcpretty -c;
  #- xcodebuild -workspace "$WORKSPACE" -scheme "PopcornTime iOS" -sdk "$IOS_SDK" -configuration Release | xcpretty -c;
