#!/bin/bash

export SCRIPT_DIR=$(dirname "$0")

set -e

cd "$(dirname "$0")/.."

if [ -f ".ruby-version" ] && [ -z "$(rbenv version-name 2>/dev/null)" ]; then
  echo "==> Installing Ruby..."
  rbenv install --skip-existing
  which bundle >/dev/null 2>&1  || {
    gem install bundler
    rbenv rehash
  }
fi

if [ -f "Gemfile" ]; then
  echo "==> Installing gem dependencies..."
  bundle install
fi

if [ -f "Podfile" ]; then
  echo "==> Installing pod dependencies..."
  bundle exec pod install
fi

